export { default as Widget } from './widget'
// export { default as ImageWidget } from './imageWidget'
export { default as BackgroundWidget } from './backgroundWidget'
// export { default as TextWidget } from './textWidget'
export { default as DrawRectWidget } from './drawRectWidget'
// export { default as RectWidget } from './rectWidget'
export { default as LayoutWidget } from './layoutWidget'
export { default as CopiedWidget } from './copiedWidget'
export { default as PictureCarouselWidget } from './pictureCarouselWidget'
export { default as TextCarouselWidget } from './textCarouselWidget'
export { default as PilotlampWidget } from './pilotlampWidget'
export { default as TableWidget } from './tableWidget'
export { default as StraightlineWidget } from './straightlineWidget'
export { default as CommonWidget } from './commonWidget'
